Lesson 3 level 7 Tasks: 30,31,32,33
konstantins-buts/jg-java-1-online-autumn-november-monday-2020 pull request #122
Opened 2020-11-18 20:00 UTC by kaverski

2020-11-18 21:39 UTC, konstantins-buts commented on src/main/java/students/jelena_kaverska/lesson_3/level_7/task_31/Product.java
> +    Product(String name, double regularPrice, double discount){
Формально говоря (исходя из условий к задаче),через конструктор необходимо указывать только наименование товара, либо важно оставить такую возможность, например, объявив дополнительный конструктор с одним параметром `String name`.

Очень важно обращать внимание на то, какие свойства и в какой момент могут принимать значения. Если бы я хотел создать продукт, у которого в определенный момент времени есть только информация о наименовании, то стоимость и скидку я могу указать уже потом. Или, если все товары которые я создаю, должны по умолчанию идти без скидки?

В таком случае может быть много лишнего кода, который "шумит" и просто оставляет нам лишнее пространство для ошибки:

```java
// Хорошо
Product apple = new Product("Apple", 0.49, 0.0);
Product milk = new Product("Milk", 1.59, 0.2);
Product bread = new Product("Bread", 1.09, 0.0);

// Совсем хорошо
Product apple = new Product("Apple", 0.49);
Product milk = new Product("Milk", 1.59, 0.2);
Product bread = new Product("Bread", 1.09);
```

Тот случай, когда меньше - больше. 🙂

2020-11-18 21:40 UTC, konstantins-buts requested changes
См. комментарий

2020-11-19 09:16 UTC, kaverski commented on src/main/java/students/jelena_kaverska/lesson_3/level_7/task_31/Product.java
> +    Product(String name, double regularPrice, double discount){
То есть надо предусмотреть возможность создания объектов с разными свойствами, добавив разные конструкторы, в данном случае в меньшим количеством свойств, т.к. по идее скидка необязательна?

2020-11-19 15:21 UTC, konstantins-buts approved these changes

2020-11-19 15:21 UTC, merged