st_eugene_trambovich_lesson_3_level_1_and_level_2
konstantins-buts/jg-java-1-online-autumn-november-monday-2020 pull request #183
Opened 2020-11-22 12:10 UTC by EugeneTrambovich

2020-11-22 18:26 UTC, konstantins-buts commented on src/main/java/students/eugene_trambovich/lesson_2/level_3/Task_11.java
> +        int firstInteger = scanner.nextInt();
По условию требуется ввод 3-х целых чисел и расчет среднего арифметического. Кажется второй половины задачи не хватает. 😳

2020-11-22 18:27 UTC, konstantins-buts requested changes
Закончить 11 задание.

2020-12-20 16:48 UTC, EugeneTrambovich commented on src/main/java/students/eugene_trambovich/lesson_2/level_3/Task_11.java
> +        int firstInteger = scanner.nextInt();
done.

2020-12-21 12:24 UTC, konstantins-buts approved these changes

2020-12-21 12:24 UTC, merged