lesson3 level7 task32
konstantins-buts/jg-java-1-online-autumn-november-monday-2020 pull request #193
Opened 2020-11-23 09:17 UTC by Cath1177

2020-11-26 20:33 UTC, konstantins-buts commented on src/main/java/students/jekaterina_aleksejeva/level_7/task_32/BankAccount.java
> +        int money = bankAccount.getMoney();
Эту часть кода менять нельзя. 🙂 Дам подсказку: число можно преобразовать в строку. 😉

2020-11-26 20:33 UTC, konstantins-buts requested changes
См. комментарий

2020-11-28 14:52 UTC, Cath1177 commented on src/main/java/students/jekaterina_aleksejeva/level_7/task_32/BankAccount.java
> +        int money = bankAccount.getMoney();
нашла Integer.toString(number) и String.valueOf(number), отправила изменения 🙂

2020-12-03 15:34 UTC, konstantins-buts approved these changes

2020-12-03 15:34 UTC, merged