St polina ivaskevich lesson 2 level 3 task 11
konstantins-buts/jg-java-1-online-autumn-november-monday-2020 pull request #25
Opened 2020-11-13 10:25 UTC by PolinaIva99

2020-11-14 13:36 UTC, konstantins-buts commented on src/main/java/students/polina_ivashkevich/lesson_2/level_2/task_8/Name.java
> +import java.sql.SQLOutput;
Неиспользуемые import можно убирать 😉

2020-11-14 13:36 UTC, konstantins-buts commented on src/main/java/students/polina_ivashkevich/lesson_2/level_3/task_9/Integer.java
> +import java.sql.SQLOutput;
Неиспользуемые import можно убирать 😉

2020-11-14 13:36 UTC, konstantins-buts commented on src/main/java/students/polina_ivashkevich/lesson_2/level_3/task_9/Integer.java
> +import com.sun.scenario.effect.impl.sw.sse.SSEBlend_SRC_OUTPeer;
Неиспользуемые import можно убирать 😉

2020-11-14 13:38 UTC, konstantins-buts commented on src/main/java/students/polina_ivashkevich/lesson_2/level_2/task_8/Name.java
> +        s="Polina";
В задаче предполагается получения ввода от пользователя через консоль. Для того, чтобы получить произвольный текст, можно воспользоваться следующим кодом:

```java
Scanner scanner = new Scanner(System.in);
String name = scanner.next();
```

Также хочу напомнить, что желательно давать переменным максимально осмысленные названия, чтобы улучшить читаемость кода. 👍

2020-11-14 13:40 UTC, konstantins-buts commented on src/main/java/students/polina_ivashkevich/lesson_2/level_3/task_10/Radius.java
> +    public static void main(String[] args) {
В задаче предполагается получения ввода от пользователя через консоль. Для того, чтобы получить произвольный текст, можно воспользоваться следующим кодом:

```java
Scanner scanner = new Scanner(System.in);
double radius = scanner.nextDouble();
```

2020-11-14 13:49 UTC, konstantins-buts commented on src/main/java/students/polina_ivashkevich/lesson_2/level_3/task_10/Radius.java
> +        r= 7.5;
Также хорошим тоном считается объявлять переменную как можно ближе к месту ее использования. Особенно это актуально, если мы можем в эту переменную присвоить какое-то значение.

```java
// Плохо
double x;
x = 123.45;

// Хорошо
double x = 123.45;
```

Это защищает твой код от потенциальных ошибок в промежуточных действиях и просто улучшает восприятие.

2020-11-14 13:51 UTC, konstantins-buts commented on src/main/java/students/polina_ivashkevich/lesson_2/level_3/task_9/Integer.java
> +        System.out.println(z*1);
Скромная таблица умножения 😛

2020-11-14 13:51 UTC, konstantins-buts requested changes
См. комментарии

2020-11-14 14:08 UTC, konstantins-buts commented on src/main/java/students/polina_ivashkevich/lesson_2/level_3/task_9/Integer.java
> +        int z =8;
В задаче предполагается получения ввода от пользователя через консоль.

2020-12-14 16:06 UTC, PolinaIva99 commented on src/main/java/students/polina_ivashkevich/lesson_2/level_2/task_8/Name.java
> +import java.sql.SQLOutput;
fixed

2021-01-07 10:17 UTC, PolinaIva99 commented on src/main/java/students/polina_ivashkevich/lesson_2/level_3/task_9/Integer.java
> +        int z =8;
fixed

2021-01-07 15:50 UTC, konstantins-buts approved these changes

2021-01-07 15:50 UTC, merged