lesson4 level3 task10
konstantins-buts/jg-java-1-online-autumn-november-monday-2020 pull request #272
Opened 2020-11-27 09:36 UTC by Cath1177

2020-11-27 21:24 UTC, konstantins-buts commented on src/main/java/students/jekaterina_aleksejeva/lesson_4/level_3/task_10/Max.java
> +    int number1;
В случае, если мы активно пользуемся параметрами в методах, добавлять такие свойства смысла нет, поскольку конкретные аргументы будут находиться в другом классе, например демонстрационном.

2020-11-27 21:26 UTC, konstantins-buts commented on src/main/java/students/jekaterina_aleksejeva/lesson_4/level_3/task_10/MaxDemo.java
> +        System.out.println (check.maximum(check.number1, check.number2, check.number3) + " is the maximum of 3 numbers");
Достаточно в рамках метода `main()` создать 3 переменные и передать именно их в качестве аргумента. 🙂 
```java
int number1 = scanner.nextInt();
int number2 = scanner.nextInt();
int number3 = scanner.nextInt();

check.maximum(number1, number2, number3);
```

2020-11-27 21:26 UTC, konstantins-buts requested changes
См. комментарий

2020-11-27 21:28 UTC, konstantins-buts commented on src/main/java/students/jekaterina_aleksejeva/lesson_4/level_3/task_10/Max.java
> +    int number1;
Если идти в 100% ООП, тогда все 3 числа нужно задавать через конструктор или "." и вызывать метод max() без аргументов, поскольку у объекта есть весь набор свойств.

2020-11-28 14:21 UTC, Cath1177 commented on src/main/java/students/jekaterina_aleksejeva/lesson_4/level_3/task_10/MaxDemo.java
> +        System.out.println (check.maximum(check.number1, check.number2, check.number3) + " is the maximum of 3 numbers");
Спасибо :) Noted!
Исправила и отправила

2020-12-03 15:39 UTC, konstantins-buts approved these changes

2020-12-03 15:39 UTC, merged