st_eugene_trambovich_lesson_4_level_1_to_3
konstantins-buts/jg-java-1-online-autumn-november-monday-2020 pull request #339
Opened 2020-11-30 09:51 UTC by EugeneTrambovich

2020-12-03 16:34 UTC, konstantins-buts commented on src/main/java/students/eugene_trambovich/lesson_4/level_3/Task_8.java
> +        } else if (firstInteger != secondInteger && secondInteger != thirdInteger) {
А если `firstInteger = 2`, `secondInteger = 3` и `thirdInteger = 2`, будет ли корректный результат?

2020-12-03 16:34 UTC, konstantins-buts requested changes
См. комментарий

2020-12-20 17:22 UTC, EugeneTrambovich commented on src/main/java/students/eugene_trambovich/lesson_4/level_3/Task_8.java
> +        } else if (firstInteger != secondInteger && secondInteger != thirdInteger) {
fixed.
else if (firstInteger != secondInteger && firstInteger != thirdInteger && secondInteger != thirdInteger) {

2020-12-21 12:26 UTC, konstantins-buts approved these changes

2020-12-21 12:26 UTC, merged