Lesson 4 level 4 task 15
konstantins-buts/jg-java-1-online-autumn-november-monday-2020 pull request #341
Opened 2020-11-30 10:09 UTC by PolinaIva99

2020-12-03 16:36 UTC, konstantins-buts commented on src/main/java/students/polina_ivashkevich/lesson_4/level_4/task_15/Calculator.java
> +            if ((firstNumber>secondNumber)&&(firstNumber>thirdNumber)) {
Достаточно вызвать метод `calculator.compare(....)` без дублирования кода.

2020-12-03 16:36 UTC, konstantins-buts requested changes
См. комментарий

2020-12-09 16:31 UTC, konstantins-buts commented on src/main/java/students/polina_ivashkevich/lesson_4/level_4/task_15/Calculator.java
> +        }   if((firstNumber==secondNumber)&&(firstNumber>thirdNumber)){
Как все числа могут быть равны, если в условии написано, что одно больше чем другое? 😅

2020-12-14 16:15 UTC, PolinaIva99 commented
fixed

2020-12-21 12:27 UTC, konstantins-buts approved these changes

2020-12-21 12:28 UTC, merged