lesson6 level3 all tasks
konstantins-buts/jg-java-1-online-autumn-november-monday-2020 pull request #498
Opened 2020-12-10 16:38 UTC by Cath1177

2020-12-13 18:43 UTC, konstantins-buts commented on src/main/java/students/jekaterina_aleksejeva/lesson_6/level_3/ArrayService.java
> +            Arrays.sort(arr);
Предполагается самостоятельная реализация алгоритма сортировки 😳

2020-12-13 18:44 UTC, konstantins-buts commented on src/main/java/students/jekaterina_aleksejeva/lesson_6/level_3/ArrayService.java
> +            Arrays.sort(arr);
Если уж использовать готовое решение, то достаточно туда переданить массив один раз, без цикла. Иначле мы будем сортировать массив `arr.length - 1` раз 🤭

2020-12-13 18:44 UTC, konstantins-buts requested changes
См. комментарий

2020-12-14 14:06 UTC, Cath1177 commented on src/main/java/students/jekaterina_aleksejeva/lesson_6/level_3/ArrayService.java
> +            Arrays.sort(arr);
спасибо, исправила!

2020-12-21 12:25 UTC, konstantins-buts approved these changes

2020-12-21 12:25 UTC, merged