Lesson 8 level 2 task 7
konstantins-buts/jg-java-1-online-autumn-november-monday-2020 pull request #577
Opened 2020-12-30 09:43 UTC by PolinaIva99

2021-01-02 15:07 UTC, konstantins-buts commented on src/main/java/students/polina_ivashkevich/lesson_8/level_2/task_7/Director.java
> +         new Director();
Вызов родительского конструктора осуществляется при помощи ключевого слова `super`, например:
```java
  Manager() { // Конструктор класса Manager
    super(); // Вызов родительского конструктора класса Director
  }
```

2021-01-02 15:07 UTC, konstantins-buts requested changes
См. комментарий

2021-01-04 14:40 UTC, PolinaIva99 commented
fixed

2021-01-10 12:44 UTC, konstantins-buts approved these changes

2021-01-10 12:44 UTC, merged