st_eugene_trambovich_lesson_10_level_1_and_2
konstantins-buts/jg-java-1-online-autumn-november-monday-2020 pull request #755
Opened 2021-01-24 14:42 UTC by EugeneTrambovich

2021-01-24 16:24 UTC, konstantins-buts commented on src/main/java/students/eugene_trambovich/lesson_10/level_1/task_1/JavaStarLoginService.java
> +interface JavaStarLoginService {
В данном случае интерфейс должен объявлять метод - "что" можно делать. А класс должен определять его реализацию.

2021-01-24 16:25 UTC, konstantins-buts commented on src/main/java/students/eugene_trambovich/lesson_10/level_2/task_4_and_5/DayOfTheWeekDetectorDemo.java
> +        new DayOfTheWeekDetectorDemo(new DayOfTheWeekDetectorSwitchVersion()).run();
Не хватает реализации на основе массива 🙂

2021-01-24 16:25 UTC, konstantins-buts requested changes
См. комментарий

2021-01-25 11:50 UTC, EugeneTrambovich commented on src/main/java/students/eugene_trambovich/lesson_10/level_1/task_1/JavaStarLoginService.java
> +interface JavaStarLoginService {
done

2021-01-25 11:50 UTC, EugeneTrambovich commented on src/main/java/students/eugene_trambovich/lesson_10/level_2/task_4_and_5/DayOfTheWeekDetectorDemo.java
> +        new DayOfTheWeekDetectorDemo(new DayOfTheWeekDetectorSwitchVersion()).run();
done

2021-01-25 16:42 UTC, konstantins-buts approved these changes

2021-01-25 16:42 UTC, merged